# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

# Pods for GithubUsers
def app_pods
	use_frameworks!
	
	pod 'Kingfisher', '~> 7.1.0' # Download and Cache Remote Images
	pod 'Moya', '~> 15.0.0' # Network Abstraction Layer
	pod 'NotificationBannerSwift', '~> 3.0.0' # Customizable Banners
	pod 'PromiseKit', '~> 6.15.3' # Swift Promises
	pod 'SnapKit', '~> 5.0.1' # Programmatic Auto Layout
	pod 'SwiftFormat/CLI', '~> 0.48.16' # Code Formatter
end

target 'GithubUsers' do
	inhibit_all_warnings!
	
  app_pods

#	# Post Install
#	post_install do |installer|
#		installer.pods_project.targets.each do |target|
#			target.build_configurations.each do |config|
#				config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
#			end
#		end
#	end
	
end

target 'GithubUsersTests' do
	inherit! :search_paths
	
	app_pods
	
	# Pods for testing
	pod 'Nimble', '~> 9.2.1' # Matcher Framework
end

target 'GithubUsersUITests' do
	# Pods for testing
end

# Post Install
post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
		end
	end
end
